name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 54.81.140.202 >> ~/.ssh/known_hosts
      shell: bash

    - name: Copy app.py to EC2
      run: |
        scp -i ~/.ssh/id_rsa app.py ec2-user@54.81.140.202:/home/ec2-user/
      shell: bash

    - name: Run app.py on EC2
      run: |
        ssh -i ~/.ssh/id_rsa ec2-user@54.81.140.202 "python3 /home/ec2-user/app.py"
      shell: bash
