name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H 35.175.140.35 >> ~/.ssh/known_hosts

    - name: Copy app to EC2
      run: |
        scp app.py ec2-user@35.175.140.35:/home/ec2-user/

    - name: Run script on EC2
      run: |
        ssh ec2-user@35.175.140.35 "python3 /home/ec2-user/app.py"
